# Generated by tools/generate_normalization_v1.py. DO NOT EDIT.
from __future__ import annotations
import hashlib
import json
from pathlib import Path

NORMALIZATION_VERSION = 1
RESOLVER_CONTRACT_VERSION = 1
UNICODE_VERSION = "15.1.0"
CONTRACT_SHA256 = "5899eac0b1207a3ecf10cedfff5c984d8e0c188267073f125347b307e95f4f52"
_DATA_PATH = Path(__file__).resolve().parent / "Fixtures/normalization-v1-data.json"

class NormalizationV1Error(ValueError):
    pass

def _load():
    raw = _DATA_PATH.read_bytes()
    actual = hashlib.sha256(raw).hexdigest()
    if actual != CONTRACT_SHA256:
        raise RuntimeError(f"normalization-v1 data digest mismatch: {actual}")
    root = json.loads(raw)
    resolver = root["resolverContract"]
    return (
        tuple(tuple(v) for v in root["acceptedInputRanges"]),
        tuple(tuple(v) for v in root["normalizationOutputRanges"]),
        {int(k): tuple(v) for k, v in root["decomposition"].items()},
        {int(k): int(v) for k, v in root["combiningClass"].items()},
        {tuple(int(p) for p in k.split(",")): int(v) for k, v in root["composition"].items()},
        {int(k): tuple(v) for k, v in root["caseFolding"].items()},
        {int(k): int(v) for k, v in root["punctuationPolicy"].items()},
        frozenset(root["whiteSpace"]),
        tuple(tuple(v) for v in resolver["letterRanges"]),
        frozenset(resolver["combiningMarks"]),
        frozenset(resolver["punctuation"]),
        int(resolver["maxScalars"]),
        int(resolver["maxTokens"]),
    )

(_RANGES, _OUTPUT_RANGES, _DECOMPOSITION, _COMBINING, _COMPOSITION, _FOLDING, _PUNCTUATION, _WHITESPACE, _LETTER_RANGES, _LOOKUP_MARKS, _LOOKUP_PUNCTUATION, _MAX_SCALARS, _MAX_TOKENS) = _load()

def _in_ranges(point: int, ranges) -> bool:
    return any(start <= point <= end for start, end in ranges)

def try_normalize_form(value: str) -> str | None:
    if not isinstance(value, str):
        return None
    points = [ord(character) for character in value]
    if any(not _in_ranges(point, _RANGES) for point in points):
        return None
    decomposed = [child for point in points for child in _DECOMPOSITION.get(point, (point,))]
    ordered: list[int] = []
    segment_start = 0
    for point in decomposed:
        ccc = _COMBINING.get(point, 0)
        ordered.append(point)
        if ccc == 0:
            segment_start = len(ordered)
        else:
            index = len(ordered) - 1
            while index > segment_start and _COMBINING.get(ordered[index - 1], 0) > ccc:
                ordered[index - 1], ordered[index] = ordered[index], ordered[index - 1]
                index -= 1
    composed: list[int] = []
    starter_index: int | None = None
    last_ccc = 0
    for point in ordered:
        ccc = _COMBINING.get(point, 0)
        composite = (_COMPOSITION.get((composed[starter_index], point)) if starter_index is not None and (last_ccc < ccc or last_ccc == 0) else None)
        if composite is not None:
            composed[starter_index] = composite
            continue
        composed.append(point)
        if ccc == 0:
            starter_index = len(composed) - 1
            last_ccc = 0
        else:
            last_ccc = ccc
    punctuated = [_PUNCTUATION.get(point, point) for point in composed]
    folded = [child for point in punctuated for child in _FOLDING.get(point, (point,))]
    output: list[int] = []
    pending_space = False
    for point in folded:
        if point in _WHITESPACE:
            pending_space = bool(output)
        else:
            if pending_space:
                output.append(0x20)
            output.append(point)
            pending_space = False
    if any(not _in_ranges(point, _OUTPUT_RANGES) for point in output):
        return None
    return "".join(chr(point) for point in output)

def normalize_form(value: str) -> str:
    normalized = try_normalize_form(value)
    if normalized is None:
        raise NormalizationV1Error("input or normalized output is outside normalization-v1")
    return normalized

def try_normalize_lookup_key(value: str) -> str | None:
    normalized = try_normalize_form(value)
    if normalized is None:
        return None
    points = [ord(character) for character in normalized]
    if not 1 <= len(points) <= _MAX_SCALARS:
        return None
    tokens = normalized.split(" ")
    if not 1 <= len(tokens) <= _MAX_TOKENS or any(not token for token in tokens):
        return None
    surface_has_letter = False
    for token in tokens:
        token_points = [ord(character) for character in token]
        previous_was_mark = False
        for index, point in enumerate(token_points):
            if _in_ranges(point, _LETTER_RANGES):
                surface_has_letter = True
                previous_was_mark = False
            elif 0x30 <= point <= 0x39:
                previous_was_mark = False
            elif point in _LOOKUP_MARKS:
                if index == 0 or previous_was_mark or not _in_ranges(token_points[index - 1], _LETTER_RANGES):
                    return None
                previous_was_mark = True
            elif point == 0x2E:
                if index == 0 or not (_in_ranges(token_points[index - 1], _LETTER_RANGES) or 0x30 <= token_points[index - 1] <= 0x39 or token_points[index - 1] in _LOOKUP_MARKS):
                    return None
                if index < len(token_points) - 1 and not ((_in_ranges(token_points[index + 1], _LETTER_RANGES) or 0x30 <= token_points[index + 1] <= 0x39) or (token_points[index + 1] == 0x2D and index + 2 < len(token_points) and (_in_ranges(token_points[index + 2], _LETTER_RANGES) or 0x30 <= token_points[index + 2] <= 0x39))):
                    return None
                previous_was_mark = False
            elif point == 0x2F:
                if index == 0 or index == len(token_points) - 1 or not (_in_ranges(token_points[index - 1], _LETTER_RANGES) or 0x30 <= token_points[index - 1] <= 0x39 or token_points[index - 1] in _LOOKUP_MARKS) or not (_in_ranges(token_points[index + 1], _LETTER_RANGES) or 0x30 <= token_points[index + 1] <= 0x39):
                    return None
                previous_was_mark = False
            elif point == 0x27:
                previous = token_points[index - 1] if index > 0 else None
                following = token_points[index + 1] if index < len(token_points) - 1 else None
                previous_atom = previous is not None and (_in_ranges(previous, _LETTER_RANGES) or 0x30 <= previous <= 0x39 or previous in _LOOKUP_MARKS)
                following_atom = following is not None and (_in_ranges(following, _LETTER_RANGES) or 0x30 <= following <= 0x39)
                if previous in {0x27, 0x2E, 0x2F} or following in {0x27, 0x2E, 0x2F}:
                    return None
                if previous == 0x2D and not (index >= 2 and (_in_ranges(token_points[index - 2], _LETTER_RANGES) or 0x30 <= token_points[index - 2] <= 0x39 or token_points[index - 2] in _LOOKUP_MARKS) and following_atom):
                    return None
                if following == 0x2D and not (previous_atom and index + 2 < len(token_points) and (_in_ranges(token_points[index + 2], _LETTER_RANGES) or 0x30 <= token_points[index + 2] <= 0x39)):
                    return None
                if not (previous_atom or following_atom):
                    return None
                previous_was_mark = False
            elif point == 0x2D:
                if index == 0 or index == len(token_points) - 1:
                    return None
                previous, following = token_points[index - 1], token_points[index + 1]
                ordinary = (_in_ranges(previous, _LETTER_RANGES) or 0x30 <= previous <= 0x39 or previous in _LOOKUP_MARKS) and (_in_ranges(following, _LETTER_RANGES) or 0x30 <= following <= 0x39)
                after_apostrophe = previous == 0x27 and index >= 2 and (_in_ranges(token_points[index - 2], _LETTER_RANGES) or 0x30 <= token_points[index - 2] <= 0x39 or token_points[index - 2] in _LOOKUP_MARKS) and (_in_ranges(following, _LETTER_RANGES) or 0x30 <= following <= 0x39)
                before_apostrophe = following == 0x27 and index + 2 < len(token_points) and (_in_ranges(previous, _LETTER_RANGES) or 0x30 <= previous <= 0x39 or previous in _LOOKUP_MARKS) and (_in_ranges(token_points[index + 2], _LETTER_RANGES) or 0x30 <= token_points[index + 2] <= 0x39)
                after_period = previous == 0x2E and index >= 2 and (_in_ranges(token_points[index - 2], _LETTER_RANGES) or 0x30 <= token_points[index - 2] <= 0x39 or token_points[index - 2] in _LOOKUP_MARKS) and (_in_ranges(following, _LETTER_RANGES) or 0x30 <= following <= 0x39)
                if not (ordinary or after_apostrophe or before_apostrophe or after_period):
                    return None
                previous_was_mark = False
            else:
                return None
    if not surface_has_letter:
        if len(tokens) != 1 or 0x2F not in token_points or any(not (0x30 <= point <= 0x39 or point == 0x2F) for point in token_points):
            return None
    return normalized

def normalize_lookup_key(value: str) -> str:
    normalized = try_normalize_lookup_key(value)
    if normalized is None:
        raise NormalizationV1Error("input is not a valid normalization-v1 resolver surface")
    return normalized

def is_valid_resolver_surface(value: str) -> bool:
    return try_normalize_lookup_key(value) is not None
